services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medium
    ports:
      - '5434:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local